Синицын А., БПМ161, 21 вариант

3.1.21


In [2]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
%matplotlib inline

Задание значений матрицы А и вектора b

In [11]:
N = 21
n = 6

b = np.array([N]*n)*1.0
c = np.array([[0.1*N*i*j for j in range(1, n + 1)] for i in range(1, n + 1)])
#print(c[0,0])
#A = np.array([[1000/(3*c[i,j]**2 + c[i,j]**3) for j in range(0, n)] for i in range(0, n)])
A = 1000/(3*c**2 + c**3)

print(A)
print(b)

[[4.44622293e+01 7.87351978e+00 2.70916810e+00 1.24318733e+00
  6.71873688e-01 4.03770245e-01]
 [7.87351978e+00 1.24318733e+00 4.03770245e-01 1.78943631e-01
  9.44822373e-02 5.58405658e-02]
 [2.70916810e+00 4.03770245e-01 1.27829849e-01 5.58405658e-02
  2.92118995e-02 1.71536379e-02]
 [1.24318733e+00 1.78943631e-01 5.58405658e-02 2.42013928e-02
  1.25976316e-02 7.37220953e-03]
 [6.71873688e-01 9.44822373e-02 2.92118995e-02 1.25976316e-02
  6.53714939e-03 3.81746413e-03]
 [4.03770245e-01 5.58405658e-02 1.71536379e-02 7.37220953e-03
  3.81746413e-03 2.22604461e-03]]
[21. 21. 21. 21. 21. 21.]


Решение системы уравнений

In [13]:
x = np.linalg.solve(A, b)
print(x)

[ 5.83328394e+05 -1.28347866e+08  2.87812060e+09 -1.71784680e+10
  3.55160291e+10 -2.30797857e+10]


Число обусловленности

In [14]:
cond = np.linalg.cond(A, p = np.inf)
cond

3749057143257.382

Вектор b с погрешностями

In [16]:
e = 1e-3
bi = np.array([b for i in range(n)])

for i in range(n):
    bi[i][i] += e

print(bi)

[[21.001 21.    21.    21.    21.    21.   ]
 [21.    21.001 21.    21.    21.    21.   ]
 [21.    21.    21.001 21.    21.    21.   ]
 [21.    21.    21.    21.001 21.    21.   ]
 [21.    21.    21.    21.    21.001 21.   ]
 [21.    21.    21.    21.    21.    21.001]]


Решение системы с погрешностями

In [18]:
xi = np.array([np.linalg.solve(A, bj) for bj in bi])
print(xi)

[[ 5.83328390e+05 -1.28347865e+08  2.87812057e+09 -1.71784678e+10
   3.55160287e+10 -2.30797855e+10]
 [ 5.83329600e+05 -1.28348185e+08  2.87812831e+09 -1.71785159e+10
   3.55161307e+10 -2.30798530e+10]
 [ 5.83297515e+05 -1.28340161e+08  2.87793906e+09 -1.71773554e+10
   3.55136908e+10 -2.30782491e+10]
 [ 5.83527182e+05 -1.28395773e+08  2.87923315e+09 -1.71852326e+10
   3.55301759e+10 -2.30890508e+10]
 [ 5.82896764e+05 -1.28246240e+08  2.87578230e+09 -1.71643212e+10
   3.54865355e+10 -2.30605106e+10]
 [ 5.83618690e+05 -1.28415084e+08  2.87965727e+09 -1.71877331e+10
   3.55353042e+10 -2.30923645e+10]]


Вектор относительных погрешностей

In [19]:
d = np.array([np.linalg.norm(x - xj, ord = np.inf)/np.linalg.norm(x, ord = np.inf) for xj in xi])
d

array([1.21531139e-08, 2.86140107e-06, 6.58378951e-05, 3.98321703e-04,
       8.30430062e-04, 5.42716054e-04])

Индекс компоненты, оказывающей наибольшее влияние на погрешность решения

In [21]:
i = np.argmax(d)
i

4

Теоретическая погрешность решения

In [22]:
dt = cond*np.linalg.norm(b - bi, ord = np.inf)/np.linalg.norm(b, ord = np.inf)
dt

178526530.6315221

Практическая погрешность решения

In [23]:
d[i]

0.000830430062475337

Теоритическая погрешность решения много больше практической, как и должно быть

3.5.6

Задание системы

In [24]:
n = 25
m = 10

f = lambda i, j: (i + j)/(m + n) if i != j else n + m**2 + j/m + i/n

A = np.array([[f(i, j) for i in range(1, n + 1)] for j in range(1, n + 1)])
b = np.array([(i*i - n) for i in range(1, n + 1)])

print(b)

[-24 -21 -16  -9   0  11  24  39  56  75  96 119 144 171 200 231 264 299
 336 375 416 459 504 551 600]


Метод Холецкого

In [29]:
L = np.linalg.cholesky(A)
L_T = L.transpose()

Решение

In [30]:
y = np.linalg.solve(L, b)
x = np.linalg.solve(L_T, y)
print(x)

[-0.35440646 -0.3376128  -0.30487312 -0.25621903 -0.19168209 -0.11129375
 -0.01508538  0.09691172  0.22466633  0.36814734  0.52732368  0.70216441
  0.89263863  1.09871555  1.32036444  1.55755465  1.81025564  2.07843691
  2.36206807  2.6611188   2.97555886  3.30535807  3.65048637  4.01091373
  4.38661024]


3.6.5

In [31]:
M = 5
n = 45
m = 4
t = np.array([0.0001, 1, 10000])

def q(M):
    return 0.993 + (-1)**M*M*(0.0001)

f = lambda i, j, t: q(M) if i != j else q(M) + t

def A(t):
    return np.array([[f(i, j, t) for i in range(1, n + 1)] for j in range(1, n + 1)])

b = np.array([q(M)**(n+1-j) for j in range(1, n + 1)])


Метод Гаусса